# Generated by Django 3.2.3 on 2021-05-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='branch',
        ),
    ]
